DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS pages;
DROP TABLE IF EXISTS tenants;
